name: Setup Poetry
author: Alfi Maulana
description: Set up a specific version of Poetry
branding:
  color: black
  icon: terminal
inputs:
  version:
    description: Poetry version to be set up
    required: false
    default: latest
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        if [ '${{ inputs.version }}' == latest ]; then
          pipx install poetry
        else
          pipx install poetry==${{ inputs.version }}
        fi
