name: Setup Poetry
author: Alfi Maulana
description: Set up a specific version of Poetry
branding:
  color: black
  icon: terminal
runs:
  using: composite
  steps:
    - shell: bash
      run: pipx install poetry
