name: Action
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  test:
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: [windows, ubuntu, macos]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.0.0

      - name: Poetry should not be available
        shell: bash
        run: "! poetry --version"

      - name: Setup Poetry
        uses: ./

      - name: Poetry should be available
        shell: bash
        run: poetry --version
